In [4]:
import sys                                                                                                                                                                             
import pandas as pd                                                                                                                                                                    
import matplotlib as mpl                                                                                                                                                               
import matplotlib.pyplot as plt                                                                                                                                                        
import os                                                                                                                                                                              
import numpy as np   

# How to compute BR (ZH and ttH)

BR(H->ZZ->2L2X) = BR(H->4L) + BR(H->2L2q) + BR(H->ZZ*->2L2nu) x BR(H->2L2nu) / [ BR(H->ZZ*->2L2nu) + BR(H->WW*->2L2nu) ] 
where BR(H->4L) BR(H->2L2q) and BR(H->2L2nu) are taken from the YR4 Twikis.

BR column also includes the gen filter efficiency (0.15038 for ZH and 0.1544 for ttH) (old values)

BR values taken from YR4: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageBR

In [5]:
# values from YR4
# BR of H120, H124, H124.5, H125, H125.5, H126, H130

# H->4l, l=e, mu, tau 
br_Hto4l = np.array([1.659e-04, 2.502e-04, 2.622e-04, 2.745e-04, 2.872e-04, 3.133e-04, 4.124e-04]) 

# H->2l2q, l = e, mu, tau
br_Hto2l2q = np.array([2.200e-03, 3.337e-03, 3.500e-03, 3.668e-03, 3.840e-03, 4.016e-03, 5.545e-03])

# H->2l2nu, l = e, mu, tau
br_Hto2l2nu = np.array([1.526e-02, 2.160e-02, 2.248e-02, 2.338e-02, 2.429e-02, 2.523e-02, 3.323e-02])

# H->ZZ
br_HtoZZ = np.array([1.572e-02, 2.383e-02, 2.499e-02, 2.619e-02, 2.741e-02, 2.866e-02, 3.955e-02])

# H->WW
br_HtoWW = np.array([1.405e-01, 1.977e-01, 2.056e-01, 2.137e-01, 2.219e-01, 2.303e-01, 3.021e-01])

# values from the PDG
# Z->ll
br_Ztoll =  3.3658e-02
# Z->nunu (invisible)
br_Ztonunu = 20e-02
# W->lnu
br_Wtolnu = 10.86e-02

In [6]:
br_HtoZZto2l2nu = br_HtoZZ * 2. * br_Ztoll * br_Ztonunu * 2.

In [7]:
br_HtoZZto2l2nu

array([0.00042328, 0.00064166, 0.00067289, 0.0007052 , 0.00073805,
       0.00077171, 0.00106494])

In [8]:
br_HtoWWto2l2nu = br_HtoWW * 2. * br_Wtolnu * br_Wtolnu * 2.

In [9]:
br_HtoWWto2l2nu

array([0.00662821, 0.00932666, 0.00969935, 0.01008148, 0.01046832,
       0.0108646 , 0.01425182])

### Results

In [10]:
br_2l2nu_temp = br_HtoZZto2l2nu * br_Hto2l2nu
br_2l2nu_temp1 = br_HtoZZto2l2nu + br_HtoWWto2l2nu
br_2l2nu_temp2 = br_2l2nu_temp / br_2l2nu_temp1

In [11]:
BR_HtoZZto2l2X = br_Hto4l + br_Hto2l2q + br_2l2nu_temp2

In [12]:
BR_HtoZZto2l2X

array([0.00328192, 0.00497758, 0.00522057, 0.00547102, 0.00572694,
       0.00600253, 0.00826781])

### Filter efficiency

In [13]:
f_eff_ZH = 0.154

In [14]:
BR_HtoZZto2l2X * f_eff_ZH

array([0.00050542, 0.00076655, 0.00080397, 0.00084254, 0.00088195,
       0.00092439, 0.00127324])

## Filter Efficiency (29/1/2024 update)

In [15]:
# filter eff computed by running over 100k events
# in total 100k events are generated and 
# out of those near 15% events are the one selected by our filter, providing us these numbers
# all come with ~0.32% uncertainty

# numbers for mH 120, 124, 124.5, 125, 125.5, 126, 130
f_eff_arr = [0.15103, 0.15093, 0.15069, 0.15012, 0.15058, 0.15045, 0.15003]

In [16]:
BR_HtoZZto2l2X * f_eff_arr

array([0.00049567, 0.00075127, 0.00078669, 0.00082131, 0.00086236,
       0.00090308, 0.00124042])

# try to reproduce BR from old csv files

YR3: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageBR2014

In [17]:
# values from YR3 
# BR of H120, H124, H125, H126, H130

br_Hto4l_YR3 = np.array([1.67e-04, 2.52e-04, 2.76e-04, 3.02e-04, 4.14e-04])
br_Hto2l2q_YR3 = np.array([2.22e-03, 3.37e-03, 3.70e-03, 4.05e-03, 5.59e-03])
br_Hto2l2nu_YR3 = np.array([1.53e-02, 2.16e-02, 2.34e-02, 2.53e-02, 3.32e-02])


br_HtoZZ_YR3 = np.array([1.59e-02, 2.41e-02, 2.64e-02, 2.89e-02, 3.98e-02])
br_HtoWW_YR3 = np.array([1.41e-01, 1.99e-01, 2.15e-01, 2.31e-01, 3.03e-01])

In [18]:
br_HtoZZto2l2nu_YR3 = br_HtoZZ_YR3 * 2. * br_Ztoll * br_Ztonunu * 2.
br_HtoWWto2l2nu_YR3 = br_HtoWW_YR3 * 2. * br_Wtolnu * br_Wtolnu * 2.

In [19]:
br_HtoZZto2l2nu_YR3

array([0.00042813, 0.00064893, 0.00071086, 0.00077817, 0.00107167])

In [20]:
br_HtoWWto2l2nu_YR3

array([0.00665179, 0.00938799, 0.01014281, 0.01089762, 0.01429428])

### results YR3

In [21]:
br_2l2nu_temp_YR3 = br_HtoZZto2l2nu_YR3 * br_Hto2l2nu_YR3
br_2l2nu_temp1_YR3 = br_HtoZZto2l2nu_YR3 + br_HtoWWto2l2nu_YR3
br_2l2nu_temp2_YR3 = br_2l2nu_temp_YR3 / br_2l2nu_temp1_YR3

In [22]:
BR_HtoZZto2l2X_YR3 = br_Hto4l_YR3 + br_Hto2l2q_YR3 + br_2l2nu_temp2_YR3

In [23]:
BR_HtoZZto2l2X_YR3

array([0.00331221, 0.00501852, 0.00550858, 0.0060382 , 0.00831947])

### multiplied for filter eff (old values)

In [24]:
BR_ZH = BR_HtoZZto2l2X_YR3 * 0.15038

In [25]:
BR_ZH

array([0.00049809, 0.00075469, 0.00082838, 0.00090803, 0.00125108])

In [26]:
BR_ttH = BR_HtoZZto2l2X_YR3 * 0.1544

In [27]:
BR_ttH

array([0.0005114 , 0.00077486, 0.00085052, 0.0009323 , 0.00128453])